name: Send Movie Poll

# Controls when the workflow will run
on:
  schedule:
    # At 12:00 PM, only on Sunday, October through December
    - cron: '0 16 * 10-12 3'
    
  workflow_dispatch:

jobs:
  send-poll:
    runs-on: ubuntu-latest
    environment: Action
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Send poll
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GOOGLE_SHEETS_ACCESS: ${{ secrets.GOOGLE_SHEETS_ACCESS }}
        run: dotnet run --project src/MoviePollBot --configuration Release


      
